/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;
using ThriftStructs;

namespace ThriftServices
{
    public partial class ChatService
    {
        public interface ISync
        {
            void enviarMensaje(TMensaje mensajeEnviado);
        }

        public interface Iface : ISync
        {
#if SILVERLIGHT
      IAsyncResult Begin_enviarMensaje(AsyncCallback callback, object state, TMensaje mensajeEnviado);
      void End_enviarMensaje(IAsyncResult asyncResult);
#endif
        }

        public class Client : IDisposable, Iface
        {
            public Client(TProtocol prot) : this(prot, prot)
            {
            }

            public Client(TProtocol iprot, TProtocol oprot)
            {
                iprot_ = iprot;
                oprot_ = oprot;
            }

            protected TProtocol iprot_;
            protected TProtocol oprot_;
            protected int seqid_;

            public TProtocol InputProtocol
            {
                get { return iprot_; }
            }
            public TProtocol OutputProtocol
            {
                get { return oprot_; }
            }


            #region " IDisposable Support "
            private bool _IsDisposed;

            // IDisposable
            public void Dispose()
            {
                Dispose(true);
            }


            protected virtual void Dispose(bool disposing)
            {
                if (!_IsDisposed)
                {
                    if (disposing)
                    {
                        if (iprot_ != null)
                        {
                            ((IDisposable)iprot_).Dispose();
                        }
                        if (oprot_ != null)
                        {
                            ((IDisposable)oprot_).Dispose();
                        }
                    }
                }
                _IsDisposed = true;
            }
            #endregion



#if SILVERLIGHT
      public IAsyncResult Begin_enviarMensaje(AsyncCallback callback, object state, TMensaje mensajeEnviado)
      {
        return send_enviarMensaje(callback, state, mensajeEnviado);
      }

      public void End_enviarMensaje(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
      }

#endif

            public void enviarMensaje(TMensaje mensajeEnviado)
            {
#if !SILVERLIGHT
                send_enviarMensaje(mensajeEnviado);

#else
        var asyncResult = Begin_enviarMensaje(null, null, mensajeEnviado);

#endif
            }
#if SILVERLIGHT
      public IAsyncResult send_enviarMensaje(AsyncCallback callback, object state, TMensaje mensajeEnviado)
#else
            public void send_enviarMensaje(TMensaje mensajeEnviado)
#endif
            {
                oprot_.WriteMessageBegin(new TMessage("enviarMensaje", TMessageType.Oneway, seqid_));
                enviarMensaje_args args = new enviarMensaje_args();
                args.MensajeEnviado = mensajeEnviado;
                args.Write(oprot_);
                oprot_.WriteMessageEnd();
#if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
#else
                oprot_.Transport.Flush();
#endif
            }

        }
        public class Processor : TProcessor
        {
            public Processor(ISync iface)
            {
                iface_ = iface;
                processMap_["enviarMensaje"] = enviarMensaje_Process;
            }

            protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
            private ISync iface_;
            protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

            public bool Process(TProtocol iprot, TProtocol oprot)
            {
                try
                {
                    TMessage msg = iprot.ReadMessageBegin();
                    ProcessFunction fn;
                    processMap_.TryGetValue(msg.Name, out fn);
                    if (fn == null)
                    {
                        TProtocolUtil.Skip(iprot, TType.Struct);
                        iprot.ReadMessageEnd();
                        TApplicationException x = new TApplicationException(TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
                        oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
                        x.Write(oprot);
                        oprot.WriteMessageEnd();
                        oprot.Transport.Flush();
                        return true;
                    }
                    fn(msg.SeqID, iprot, oprot);
                }
                catch (IOException)
                {
                    return false;
                }
                return true;
            }

            public void enviarMensaje_Process(int seqid, TProtocol iprot, TProtocol oprot)
            {
                enviarMensaje_args args = new enviarMensaje_args();
                args.Read(iprot);
                iprot.ReadMessageEnd();
                try
                {
                    iface_.enviarMensaje(args.MensajeEnviado);
                }
                catch (TTransportException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine("Error occurred in processor:");
                    Console.Error.WriteLine(ex.ToString());
                }
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class enviarMensaje_args : TBase
        {
            private TMensaje _mensajeEnviado;

            public TMensaje MensajeEnviado
            {
                get
                {
                    return _mensajeEnviado;
                }
                set
                {
                    __isset.mensajeEnviado = true;
                    this._mensajeEnviado = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset
            {
                public bool mensajeEnviado;
            }

            public enviarMensaje_args()
            {
            }

            public void Read(TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop)
                        {
                            break;
                        }
                        switch (field.ID)
                        {
                            case 1:
                                if (field.Type == TType.Struct)
                                {
                                    MensajeEnviado = new TMensaje();
                                    MensajeEnviado.Read(iprot);
                                }
                                else
                                {
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default:
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot)
            {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("enviarMensaje_args");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();
                    if (MensajeEnviado != null && __isset.mensajeEnviado)
                    {
                        field.Name = "mensajeEnviado";
                        field.Type = TType.Struct;
                        field.ID = 1;
                        oprot.WriteFieldBegin(field);
                        MensajeEnviado.Write(oprot);
                        oprot.WriteFieldEnd();
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString()
            {
                StringBuilder __sb = new StringBuilder("enviarMensaje_args(");
                bool __first = true;
                if (MensajeEnviado != null && __isset.mensajeEnviado)
                {
                    if (!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("MensajeEnviado: ");
                    __sb.Append(MensajeEnviado == null ? "<null>" : MensajeEnviado.ToString());
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }

    }
}
