/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftStructs
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TConexion : TBase
  {
    private string _direccionIP;
    private int _idSalon;
    private int _idCuenta;
    private string _nombre;

    public string DireccionIP
    {
      get
      {
        return _direccionIP;
      }
      set
      {
        __isset.direccionIP = true;
        this._direccionIP = value;
      }
    }

    public int IdSalon
    {
      get
      {
        return _idSalon;
      }
      set
      {
        __isset.idSalon = true;
        this._idSalon = value;
      }
    }

    public int IdCuenta
    {
      get
      {
        return _idCuenta;
      }
      set
      {
        __isset.idCuenta = true;
        this._idCuenta = value;
      }
    }

    public string Nombre
    {
      get
      {
        return _nombre;
      }
      set
      {
        __isset.nombre = true;
        this._nombre = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool direccionIP;
      public bool idSalon;
      public bool idCuenta;
      public bool nombre;
    }

    public TConexion() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                DireccionIP = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                IdSalon = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                IdCuenta = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Nombre = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TConexion");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (DireccionIP != null && __isset.direccionIP) {
          field.Name = "direccionIP";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(DireccionIP);
          oprot.WriteFieldEnd();
        }
        if (__isset.idSalon) {
          field.Name = "idSalon";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdSalon);
          oprot.WriteFieldEnd();
        }
        if (__isset.idCuenta) {
          field.Name = "idCuenta";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdCuenta);
          oprot.WriteFieldEnd();
        }
        if (Nombre != null && __isset.nombre) {
          field.Name = "nombre";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Nombre);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TConexion(");
      bool __first = true;
      if (DireccionIP != null && __isset.direccionIP) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DireccionIP: ");
        __sb.Append(DireccionIP);
      }
      if (__isset.idSalon) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdSalon: ");
        __sb.Append(IdSalon);
      }
      if (__isset.idCuenta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdCuenta: ");
        __sb.Append(IdCuenta);
      }
      if (Nombre != null && __isset.nombre) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Nombre: ");
        __sb.Append(Nombre);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
