/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftStructs
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TEEImpartidaView : TBase
  {
    private int _idEEImpartida;
    private string _ee;
    private string _maestro;
    private int _idCuenta;

    public int IdEEImpartida
    {
      get
      {
        return _idEEImpartida;
      }
      set
      {
        __isset.idEEImpartida = true;
        this._idEEImpartida = value;
      }
    }

    public string Ee
    {
      get
      {
        return _ee;
      }
      set
      {
        __isset.ee = true;
        this._ee = value;
      }
    }

    public string Maestro
    {
      get
      {
        return _maestro;
      }
      set
      {
        __isset.maestro = true;
        this._maestro = value;
      }
    }

    public int IdCuenta
    {
      get
      {
        return _idCuenta;
      }
      set
      {
        __isset.idCuenta = true;
        this._idCuenta = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool idEEImpartida;
      public bool ee;
      public bool maestro;
      public bool idCuenta;
    }

    public TEEImpartidaView() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                IdEEImpartida = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Ee = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Maestro = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                IdCuenta = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TEEImpartidaView");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.idEEImpartida) {
          field.Name = "idEEImpartida";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdEEImpartida);
          oprot.WriteFieldEnd();
        }
        if (Ee != null && __isset.ee) {
          field.Name = "ee";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Ee);
          oprot.WriteFieldEnd();
        }
        if (Maestro != null && __isset.maestro) {
          field.Name = "maestro";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Maestro);
          oprot.WriteFieldEnd();
        }
        if (__isset.idCuenta) {
          field.Name = "idCuenta";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdCuenta);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TEEImpartidaView(");
      bool __first = true;
      if (__isset.idEEImpartida) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdEEImpartida: ");
        __sb.Append(IdEEImpartida);
      }
      if (Ee != null && __isset.ee) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Ee: ");
        __sb.Append(Ee);
      }
      if (Maestro != null && __isset.maestro) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Maestro: ");
        __sb.Append(Maestro);
      }
      if (__isset.idCuenta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdCuenta: ");
        __sb.Append(IdCuenta);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
