/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftStructs
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TMensaje : TBase
  {
    private string _nombreRemitente;
    private string _contenido;
    private int _idSalon;

    public string NombreRemitente
    {
      get
      {
        return _nombreRemitente;
      }
      set
      {
        __isset.nombreRemitente = true;
        this._nombreRemitente = value;
      }
    }

    public string Contenido
    {
      get
      {
        return _contenido;
      }
      set
      {
        __isset.contenido = true;
        this._contenido = value;
      }
    }

    public int IdSalon
    {
      get
      {
        return _idSalon;
      }
      set
      {
        __isset.idSalon = true;
        this._idSalon = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool nombreRemitente;
      public bool contenido;
      public bool idSalon;
    }

    public TMensaje() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                NombreRemitente = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Contenido = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                IdSalon = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TMensaje");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (NombreRemitente != null && __isset.nombreRemitente) {
          field.Name = "nombreRemitente";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(NombreRemitente);
          oprot.WriteFieldEnd();
        }
        if (Contenido != null && __isset.contenido) {
          field.Name = "contenido";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Contenido);
          oprot.WriteFieldEnd();
        }
        if (__isset.idSalon) {
          field.Name = "idSalon";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdSalon);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TMensaje(");
      bool __first = true;
      if (NombreRemitente != null && __isset.nombreRemitente) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NombreRemitente: ");
        __sb.Append(NombreRemitente);
      }
      if (Contenido != null && __isset.contenido) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Contenido: ");
        __sb.Append(Contenido);
      }
      if (__isset.idSalon) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdSalon: ");
        __sb.Append(IdSalon);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
