/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;
using ThriftStructs;

namespace ThriftCallbacks
{
  public partial class ChatCallback {
    public interface ISync {
      void recibirMensaje(TMensaje mensajeRecibido);
    }

    public interface Iface : ISync {
      #if SILVERLIGHT
      IAsyncResult Begin_recibirMensaje(AsyncCallback callback, object state, TMensaje mensajeRecibido);
      void End_recibirMensaje(IAsyncResult asyncResult);
      #endif
    }

    public class Client : IDisposable, Iface {
      public Client(TProtocol prot) : this(prot, prot)
      {
      }

      public Client(TProtocol iprot, TProtocol oprot)
      {
        iprot_ = iprot;
        oprot_ = oprot;
      }

      protected TProtocol iprot_;
      protected TProtocol oprot_;
      protected int seqid_;

      public TProtocol InputProtocol
      {
        get { return iprot_; }
      }
      public TProtocol OutputProtocol
      {
        get { return oprot_; }
      }


      #region " IDisposable Support "
      private bool _IsDisposed;

      // IDisposable
      public void Dispose()
      {
        Dispose(true);
      }
      

      protected virtual void Dispose(bool disposing)
      {
        if (!_IsDisposed)
        {
          if (disposing)
          {
            if (iprot_ != null)
            {
              ((IDisposable)iprot_).Dispose();
            }
            if (oprot_ != null)
            {
              ((IDisposable)oprot_).Dispose();
            }
          }
        }
        _IsDisposed = true;
      }
      #endregion


      
      #if SILVERLIGHT
      public IAsyncResult Begin_recibirMensaje(AsyncCallback callback, object state, TMensaje mensajeRecibido)
      {
        return send_recibirMensaje(callback, state, mensajeRecibido);
      }

      public void End_recibirMensaje(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
      }

      #endif

      public void recibirMensaje(TMensaje mensajeRecibido)
      {
        #if !SILVERLIGHT
        send_recibirMensaje(mensajeRecibido);

        #else
        var asyncResult = Begin_recibirMensaje(null, null, mensajeRecibido);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_recibirMensaje(AsyncCallback callback, object state, TMensaje mensajeRecibido)
      #else
      public void send_recibirMensaje(TMensaje mensajeRecibido)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("recibirMensaje", TMessageType.Oneway, seqid_));
        recibirMensaje_args args = new recibirMensaje_args();
        args.MensajeRecibido = mensajeRecibido;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

    }
    public class Processor : TProcessor {
      public Processor(ISync iface)
      {
        iface_ = iface;
        processMap_["recibirMensaje"] = recibirMensaje_Process;
      }

      protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
      private ISync iface_;
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public bool Process(TProtocol iprot, TProtocol oprot)
      {
        try
        {
          TMessage msg = iprot.ReadMessageBegin();
          ProcessFunction fn;
          processMap_.TryGetValue(msg.Name, out fn);
          if (fn == null) {
            TProtocolUtil.Skip(iprot, TType.Struct);
            iprot.ReadMessageEnd();
            TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
            x.Write(oprot);
            oprot.WriteMessageEnd();
            oprot.Transport.Flush();
            return true;
          }
          fn(msg.SeqID, iprot, oprot);
        }
        catch (IOException)
        {
          return false;
        }
        return true;
      }

      public void recibirMensaje_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        recibirMensaje_args args = new recibirMensaje_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        try
        {
          iface_.recibirMensaje(args.MensajeRecibido);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception ex)
        {
          Console.Error.WriteLine("Error occurred in processor:");
          Console.Error.WriteLine(ex.ToString());
        }
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class recibirMensaje_args : TBase
    {
      private TMensaje _mensajeRecibido;

      public TMensaje MensajeRecibido
      {
        get
        {
          return _mensajeRecibido;
        }
        set
        {
          __isset.mensajeRecibido = true;
          this._mensajeRecibido = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool mensajeRecibido;
      }

      public recibirMensaje_args() {
      }

      public void Read (TProtocol iprot)
      {
        iprot.IncrementRecursionDepth();
        try
        {
          TField field;
          iprot.ReadStructBegin();
          while (true)
          {
            field = iprot.ReadFieldBegin();
            if (field.Type == TType.Stop) { 
              break;
            }
            switch (field.ID)
            {
              case 1:
                if (field.Type == TType.Struct) {
                  MensajeRecibido = new TMensaje();
                  MensajeRecibido.Read(iprot);
                } else { 
                  TProtocolUtil.Skip(iprot, field.Type);
                }
                break;
              default: 
                TProtocolUtil.Skip(iprot, field.Type);
                break;
            }
            iprot.ReadFieldEnd();
          }
          iprot.ReadStructEnd();
        }
        finally
        {
          iprot.DecrementRecursionDepth();
        }
      }

      public void Write(TProtocol oprot) {
        oprot.IncrementRecursionDepth();
        try
        {
          TStruct struc = new TStruct("recibirMensaje_args");
          oprot.WriteStructBegin(struc);
          TField field = new TField();
          if (MensajeRecibido != null && __isset.mensajeRecibido) {
            field.Name = "mensajeRecibido";
            field.Type = TType.Struct;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            MensajeRecibido.Write(oprot);
            oprot.WriteFieldEnd();
          }
          oprot.WriteFieldStop();
          oprot.WriteStructEnd();
        }
        finally
        {
          oprot.DecrementRecursionDepth();
        }
      }

      public override string ToString() {
        StringBuilder __sb = new StringBuilder("recibirMensaje_args(");
        bool __first = true;
        if (MensajeRecibido != null && __isset.mensajeRecibido) {
          if(!__first) { __sb.Append(", "); }
          __first = false;
          __sb.Append("MensajeRecibido: ");
          __sb.Append(MensajeRecibido== null ? "<null>" : MensajeRecibido.ToString());
        }
        __sb.Append(")");
        return __sb.ToString();
      }

    }

  }
}
