//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClasesEnLineaEntities : DbContext
    {
        public ClasesEnLineaEntities()
            : base("name=ClasesEnLineaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<eeasistencia> eeasistencia { get; set; }
        public virtual DbSet<eeimpartida> eeimpartida { get; set; }
        public virtual DbSet<experienciaeducativa> experienciaeducativa { get; set; }
        public virtual DbSet<eeasistenciaview> eeasistenciaview { get; set; }
        public virtual DbSet<eeimpartidaview> eeimpartidaview { get; set; }
    }
}
