//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class eeimpartida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eeimpartida()
        {
            this.eeasistencia = new HashSet<eeasistencia>();
        }
    
        public int idEEImpartida { get; set; }
        public int idEE { get; set; }
        public int idCuenta { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eeasistencia> eeasistencia { get; set; }
        public virtual experienciaeducativa experienciaeducativa { get; set; }
    }
}
