/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftStructs
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TCuenta : TBase
  {
    private int _idCuenta;
    private string _nombre;
    private string _usuario;
    private string _contrasena;

    public int IdCuenta
    {
      get
      {
        return _idCuenta;
      }
      set
      {
        __isset.idCuenta = true;
        this._idCuenta = value;
      }
    }

    public string Nombre
    {
      get
      {
        return _nombre;
      }
      set
      {
        __isset.nombre = true;
        this._nombre = value;
      }
    }

    public string Usuario
    {
      get
      {
        return _usuario;
      }
      set
      {
        __isset.usuario = true;
        this._usuario = value;
      }
    }

    public string Contrasena
    {
      get
      {
        return _contrasena;
      }
      set
      {
        __isset.contrasena = true;
        this._contrasena = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool idCuenta;
      public bool nombre;
      public bool usuario;
      public bool contrasena;
    }

    public TCuenta() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                IdCuenta = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Nombre = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Usuario = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Contrasena = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TCuenta");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.idCuenta) {
          field.Name = "idCuenta";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdCuenta);
          oprot.WriteFieldEnd();
        }
        if (Nombre != null && __isset.nombre) {
          field.Name = "nombre";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Nombre);
          oprot.WriteFieldEnd();
        }
        if (Usuario != null && __isset.usuario) {
          field.Name = "usuario";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Usuario);
          oprot.WriteFieldEnd();
        }
        if (Contrasena != null && __isset.contrasena) {
          field.Name = "contrasena";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Contrasena);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TCuenta(");
      bool __first = true;
      if (__isset.idCuenta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdCuenta: ");
        __sb.Append(IdCuenta);
      }
      if (Nombre != null && __isset.nombre) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Nombre: ");
        __sb.Append(Nombre);
      }
      if (Usuario != null && __isset.usuario) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Usuario: ");
        __sb.Append(Usuario);
      }
      if (Contrasena != null && __isset.contrasena) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Contrasena: ");
        __sb.Append(Contrasena);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
